version: "3"
services:
 mongo-cooker:
  image: mongo:4.2.5
  ports:
    - "27018:27017"
  environment:
    MONGO_INITDB_DATABASE: foods
  volumes:
   - ./resources/database_entrypoint/mongodb:/docker-entrypoint-initdb.d