version: "3"
services:
 mongo-cooker:
  image: mongo:4.2.5
  ports:
    - "27018:27017"
  environment:
    MONGO_INITDB_DATABASE: foods
  volumes:
   - ./resources/database_entrypoint/mongodb:/docker-entrypoint-initdb.d
#
# zookeeper:
#  image: 'bitnami/zookeeper:latest'
#  ports:
#    - "2181:2181"
#  environment:
#    - ALLOW_ANONYMOUS_LOGIN=yes
#
# kafka:
#   image: 'bitnami/kafka:latest'
#   ports:
#     - "9092:9092"
#   environment:
#     - KAFKA_BROKER_ID=1
#     - KAFKA_LISTENERS=PLAINTEXT://:9092
#     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#     - ALLOW_PLAINTEXT_LISTENER=yes
#   depends_on:
#     - zookeeper