version: "3"
services:
 mongo-bartender:
  image: mongo:4.2.5
  ports:
    - "27019:27017"
  environment:
    MONGO_INITDB_DATABASE: drinks
  volumes:
   - ./resources/database_entrypoint/mongodb:/docker-entrypoint-initdb.d
